# Generated by Django 4.1.7 on 2023-03-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
    ]
