# Generated by Django 4.1.7 on 2023-03-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20230305_1532'),
    ]

    operations = [
    ]
