# Generated by Django 4.1.7 on 2023-03-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0001_initial'),
    ]

    operations = [
    ]
