# Generated by Django 4.1.6 on 2023-03-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='4adfefd6-db09-400c-be78-5becbdf0b203', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='2f9e5e9a-0733-4a30-b198-5243ab7adef1', max_length=255, unique=True),
        ),
    ]
