# Generated by Django 4.1.7 on 2023-03-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
    ]
