# Generated by Django 4.1.7 on 2023-03-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='bd5d5be9-3f24-4380-bf5a-e7dbfc509941', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='932b8feb-a11c-4787-a9fa-45bb4f19494a', max_length=255, unique=True),
        ),
    ]
