# Generated by Django 4.1.6 on 2023-03-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='29b4d0f7-2b63-465a-a93f-51c0a1df7de7', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='e51df647-2384-4331-9eba-bab35c908413', max_length=255, unique=True),
        ),
    ]
