# Generated by Django 4.1.7 on 2023-03-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='4d6e62dd-3775-4032-8cbe-72fa539bee1c', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='1443ab4e-b43d-43ab-aaca-e0efd89116ec', editable=False, max_length=255, unique=True),
        ),
    ]
