# Generated by Django 4.1.6 on 2023-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='682f56f6-748a-4d9c-8d55-89d56193c9c1', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.UUIDField(default='0161e85e-e20f-465b-b11c-83af88fe9c1e', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followrequests',
            name='id',
            field=models.UUIDField(default='bb56e638-01d4-4244-aa89-e823dfd940fe', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.UUIDField(default='b4c17f13-ee2d-4e5d-8a6a-c21cb90ceb36', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='fbd174a2-93c0-4ece-a171-78311874adf4', max_length=255, unique=True),
        ),
    ]
