# Generated by Django 4.1.7 on 2023-04-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='d950fb50-e1c2-4ebb-af2b-5641ca0d57a8', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.UUIDField(default='87667a41-fe66-4471-ad72-6e5941f8755a', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followrequests',
            name='id',
            field=models.UUIDField(default='c9a13878-2f31-47a6-acba-887c80d5ee3b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.UUIDField(default='95075112-31ca-4db3-91af-6945cd67d72f', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='54fc6e96-dc0a-4649-8cee-86a9db1b63b6', max_length=255, unique=True),
        ),
    ]
