# Generated by Django 3.2.18 on 2023-03-31 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0002_initial'),
    ]

    operations = [
    ]
