# Generated by Django 4.1.7 on 2023-03-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='7ecf7f33-6352-400c-846b-281c05a913c6', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.UUIDField(default='790253e1-3c2b-4590-8dc9-84c903475b81', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followrequests',
            name='id',
            field=models.UUIDField(default='d8faf728-0957-4b12-b1aa-c357b2a92281', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='b48a535c-e8ba-49f2-bf06-5e027cf56a5f', max_length=255, unique=True),
        ),
    ]
