# Generated by Django 3.2.18 on 2023-03-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0003_auto_20230330_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='87a67155-8fc7-4913-b421-c4edd63cc2c3', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.UUIDField(default='c40f28f8-0f08-494a-bad5-40cea65b940b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followrequests',
            name='id',
            field=models.UUIDField(default='8d1df6fb-9a44-4212-b4b2-74afaf62f41b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='557503d4-a3cd-4e03-a558-762333674c22', max_length=255, unique=True),
        ),
    ]
