# Generated by Django 4.1.7 on 2023-03-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0003_rename_post_posts_alter_posts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='allModels.posts'),
        ),
    ]
