# Generated by Django 4.1.6 on 2023-03-23 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0003_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
    ]
