# Generated by Django 4.1.7 on 2023-04-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0003_alter_comments_uuid_alter_followers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='f643169e-cd4c-4a44-a6bd-a617a7a660bd', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.UUIDField(default='36171486-631f-4198-b0ac-0c0597776999', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followrequests',
            name='id',
            field=models.UUIDField(default='baccab19-8d9c-4951-918a-554929ba57c5', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.UUIDField(default='c03c4179-0d58-47de-8782-86db5403a86f', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='f914629b-8c5a-43a4-8b49-5c3912b5f23f', max_length=255, unique=True),
        ),
    ]
