# Generated by Django 4.1.7 on 2023-03-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0004_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='40d25e47-1017-4c5f-b5f5-a8f140c411e4', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='11b5d4fa-88d1-448a-875a-10084a726e1e', max_length=255, unique=True),
        ),
    ]
