# Generated by Django 3.2.18 on 2023-03-31 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0004_auto_20230330_2011'),
    ]

    operations = [
    ]
