# Generated by Django 4.1.7 on 2023-03-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0004_remove_authors_last_login_alter_comments_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='bf37bca4-9e31-4803-94bf-b0923ee7e84e', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='075e3f26-dcf6-46c1-ac9e-1a22f8fbedb8', max_length=255, unique=True),
        ),
    ]
