# Generated by Django 4.1.7 on 2023-04-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0004_alter_comments_uuid_alter_followers_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('type', models.CharField(default='node', editable=False, max_length=255)),
                ('host', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Node',
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='2304c7f1-bce2-4121-941a-67a95480d750', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.UUIDField(default='b2a389a6-0bde-4f62-9cf3-77b2bc7c2954', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followrequests',
            name='id',
            field=models.UUIDField(default='a5924cfc-48b0-4b11-97cf-8eb7cd534aa5', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.UUIDField(default='419e787b-2374-40e2-a1dc-125a343510e6', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='58023465-beb8-46e2-93a8-97cc39167af2', max_length=255, unique=True),
        ),
    ]
