# Generated by Django 3.2.18 on 2023-03-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0005_auto_20230330_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='c3f6c3ba-dbe6-4387-93db-f1366e542e96', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.UUIDField(default='0e64c075-169b-4b9e-bdd8-b0397fdf6530', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followrequests',
            name='id',
            field=models.UUIDField(default='68817b45-6edb-4e00-986f-09d22149c828', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='34444cc4-b420-4093-abe9-cfbea00333f0', max_length=255, unique=True),
        ),
    ]
