# Generated by Django 4.1.7 on 2023-03-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0005_alter_authors_uuid_alter_comments_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='acfaf9f4-a8f9-4bc3-a149-66be997abc46', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='642388cf-bba1-493c-87b5-922cf1df3578', max_length=255, unique=True),
        ),
    ]
