# Generated by Django 4.1.6 on 2023-03-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0006_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='c6a95e4f-9b8c-40b6-974f-fbe14a741315', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='274f0df1-fc60-4f41-8339-5384b389cad0', max_length=255, unique=True),
        ),
    ]
