# Generated by Django 4.1.7 on 2023-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0006_rename_items_inbox_posts_alter_comments_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='6793ed57-448c-4f44-9a12-34062436b446', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='2ffd4d68-647b-4c3a-9ea4-833a973b449b', max_length=255, unique=True),
        ),
    ]
