# Generated by Django 4.1.6 on 2023-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0006_rename_items_inbox_posts_alter_comments_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='8a773600-a68b-4049-a05d-d6e98ecda20a', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='f024a016-ca15-435a-9766-e590cf9a9a3c', max_length=255, unique=True),
        ),
    ]
