# Generated by Django 4.1.7 on 2023-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0007_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='b9f81f41-3ef4-4f5b-a281-6ddef341792d', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='fbb477c6-0bb8-4a16-ad8e-7f55141f70c7', max_length=255, unique=True),
        ),
    ]
