# Generated by Django 4.1.7 on 2023-03-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0008_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='20e20011-d4a2-40c4-8d1d-6b8fc55817f9', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='8b3bbb9c-b854-4198-b02a-d7a010478db1', max_length=255, unique=True),
        ),
    ]
