# Generated by Django 4.1.7 on 2023-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0008_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='64da3d91-2aa1-4b57-9788-a46db6aa7b19', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='d50bbd31-939c-4850-9203-a3e61a28f559', max_length=255, unique=True),
        ),
    ]
