# Generated by Django 4.1.7 on 2023-03-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0009_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='3b70497e-3b0d-482f-b93d-bc34da5b9ea2', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='b69382cd-cbf4-41a9-8ca4-2caa473e2a6b', max_length=255, unique=True),
        ),
    ]
