# Generated by Django 4.1.7 on 2023-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0011_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='36c25296-b037-4bf3-8697-fd26d886bfea', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='f1452e8d-3631-4cc7-ab12-0ac62309e7e1', max_length=255, unique=True),
        ),
    ]
