# Generated by Django 4.1.7 on 2023-03-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0012_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='4bfe9c69-93db-4569-b220-36582d568058', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='4919fc08-858a-46ae-8bc5-1fbe62477805', max_length=255, unique=True),
        ),
    ]
