# Generated by Django 4.1.7 on 2023-03-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0014_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='d90dffe1-9325-4509-a3b9-2c56e6e86abc', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='667ef0a0-4305-4dcd-ab42-aa64ac15b820', max_length=255, unique=True),
        ),
    ]
