# Generated by Django 4.1.7 on 2023-03-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0016_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='0bd207ac-fcdb-45d5-9ef3-3570d7a3eb66', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='b6a2f6d1-b271-46ff-ac0d-2434615e713c', max_length=255, unique=True),
        ),
    ]
