# Generated by Django 4.1.7 on 2023-03-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allModels', '0017_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='67daccec-c214-490a-9b7c-863050a3eb88', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(blank=True, to='allModels.likes'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='c4555502-4356-4698-bf72-fb6b55529ab3', max_length=255, unique=True),
        ),
    ]
